FROM ubuntu:14.04

MAINTAINER Sebastian Peters <Sebastian.Peters@gmail.com>

RUN apt-get update

RUN apt-get -y install git
RUN apt-get -y install htop
RUN apt-get -y install unzip
RUN apt-get -y install vim
RUN apt-get -y install wget